tables = [
    # 'risk_data',

    # 挂牌修复列表
    'economic_gdp',
    'futures_basic',
    'comcn_embeddedvaluechange',
    'comcn_embeddedvalue',
    'comcn_embeddedvalueindex',
    'comcn_financespecialindexic',
    'economic_moneysupply',
    'const_keywords',
    'comcn_conceptlist',
    'const_personal',
    'comcn_bankindiconst',
    'comcn_financespecialindexsc',

    'hkland_historycashflow',
    'const_industry',
    'derived_institution_summary',
    'stk_specialtrade',
    'hkland_historytradestat',
    'index_indexprepcomponent',
    'stk_codechangeserial',
    'const_secumain',
    'const_areacode',

    'const_newsconst',
    'stk_liststatus',
    'comcn_controllingshareholders',
    'comcn_actualcontroller',
    'comcn_violationhalding',
    'const_product',
    'comcn_financespecialindex',
    'index_basicinfo',
    'comcn_msecufinance',
    'comcn_issuanceexamination',
    'stk_abbrchangeserial',
    'stk_secuchange',
    'const_industrytype',
    'const_ussecumain',
    'comcn_performanceletters',
    'comcn_bankassetsliability',
    'comcn_sharesfloatingschedule',
    'comcn_mainquarterdata',
    'stk_business',
    'comcn_bankloan',
    'comcn_bankincomeexpense',
    'const_systemconst',
    'comcn_rewardstat',
    'derived_institution_detail',
    'comcn_coconcept',
    'news_secu',
    'comcn_bankregulator',
    'comcn_relatedsh',
    'comcn_exgindustry',
    'comcn_sharefpsta',
    'comcn_sharefp',
    'comcn_dividend',
    'comcn_managersstockalteration',
    'comcn_financialreportauditingopinion',
    'comcn_performanceforecast',
    'comcn_sharestru',
    'comcn_dividendprogress',
    'comcn_stockholdingst',
    'comcn_reservereportdate',
    'comcn_guaranteedetail',
    'stk_codechange',
    'const_tradingday',
    'const_hksecumain',
    'const_secumainall',
    'comcn_leaderposition',
    'stk_7percentchange',
    'stk_specialnotice',
    'comcn_qcashflowstatement',
    'comcn_qincomestatement',
    'comcn_qfinancialindex',
    'const_jydbdeleterec',
    'comcn_fsderiveddata',
    'comcn_fspecialindicators',
    'comcn_maindatanew',
    'comcn_cashflowstatementall_jy',
    'comcn_cashflowstatement',
    'comcn_balancesheetall_jy',
    'comcn_balancesheet',
    'comcn_incomestatement',
    'comcn_incomestatementall_jy',
    'comcn_nonrecurringevent',
    'comcn_executivesholdings',
    'comcn_mainoperincome',
    'hkland_shares',
    'index_sywgindexquote',
    'index_quot_day',
    'comcn_equitychangesstatement',
    'comcn_mainshlistnew',
    'trans_valuations',

    # 测试期间暂时先不同步这一部分
    # 'stk_quotori_day',
    # 'stk_quotidxwind_day',
    # 'comcn_dindicesforvaluation',
    # 'stk_quot_day',
    # 'stk_quot_idx',
    # 'index_indexcomponentsweight',
    # 'index_weight',
    # 'index_swsindexcw'
]